---

- name: Mongodb for ubuntu
  hosts: all
  remote_user: ubuntu
  gather_facts: true
  become_user: root
  become: true
  pre_tasks:
    - name: Update and install python
      apt: 
        name: python
        update_cache: yes
        state: latest
  roles:
    - mongodb
  vars:
    mongodb_conf_bind_ip: 0.0.0.0
    mongodb_conf_port: 8090
